<section id="content">
	<div class="row wraper">
		<div class="container">
			<div class="col-xs-12 col-sm-12 col-md-3 col-lg-3">
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 list-menu pull-left">
                    <?php $this->load->view('frontend/modules/category'); ?> 
                </div>
            </div>
			<div class = "col-xs-12 col-sm-12 col-md-9 col-lg-9 product-content" id="list-content">
				<div class="product-wrap" style="">
                    <div class="wrap-2">
                        <h2>Ch&iacute;nh s&aacute;ch</h2>
                        <p>C&aacute;m ơn qu&yacute; kh&aacute;ch đ&atilde; quan t&acirc;m v&agrave; truy cập v&agrave;o website. Ch&uacute;ng t&ocirc;i t&ocirc;n trọng v&agrave; cam kết sẽ bảo mật những th&ocirc;ng tin mang t&iacute;nh ri&ecirc;ng tư của Qu&yacute; kh&aacute;ch.</p>
                        <p>Ch&iacute;nh s&aacute;ch bảo mật sẽ giải th&iacute;ch c&aacute;ch ch&uacute;ng t&ocirc;i tiếp nhận, sử dụng v&agrave; (trong trường hợp n&agrave;o đ&oacute;) tiết lộ th&ocirc;ng tin c&aacute; nh&acirc;n của Qu&yacute; kh&aacute;ch.</p>
                        <p>Bảo vệ dữ liệu c&aacute; nh&acirc;n v&agrave; g&acirc;y dựng được niềm tin cho qu&yacute; kh&aacute;ch l&agrave; vấn đề rất quan trọng với ch&uacute;ng t&ocirc;i. V&igrave; vậy, ch&uacute;ng t&ocirc;i sẽ d&ugrave;ng t&ecirc;n v&agrave; c&aacute;c th&ocirc;ng tin kh&aacute;c li&ecirc;n quan đến qu&yacute; kh&aacute;ch tu&acirc;n thủ theo nội dung của Ch&iacute;nh s&aacute;ch bảo mật. Ch&uacute;ng t&ocirc;i chỉ thu thập những th&ocirc;ng tin cần thiết li&ecirc;n quan đến giao dịch mua b&aacute;n.</p>
                        <p>Ch&uacute;ng t&ocirc;i sẽ giữ th&ocirc;ng tin của kh&aacute;ch h&agrave;ng trong thời gian luật ph&aacute;p quy định hoặc cho mục đ&iacute;ch n&agrave;o đ&oacute;. Qu&yacute; kh&aacute;ch c&oacute; thể truy cập v&agrave;o website v&agrave; tr&igrave;nh duyệt m&agrave; kh&ocirc;ng cần phải cung cấp chi tiết c&aacute; nh&acirc;n. L&uacute;c đ&oacute;, Qu&yacute; kh&aacute;ch đang ẩn danh v&agrave; ch&uacute;ng t&ocirc;i kh&ocirc;ng thể biết bạn l&agrave; ai nếu Qu&yacute; kh&aacute;ch kh&ocirc;ng đăng nhập v&agrave;o t&agrave;i khoản của m&igrave;nh.</p>
                        <p><strong>1. Thu thập th&ocirc;ng tin c&aacute; nh&acirc;n</strong></p>
                        <p>- Ch&uacute;ng t&ocirc;i thu thập, lưu trữ v&agrave; xử l&yacute; th&ocirc;ng tin của bạn cho qu&aacute; tr&igrave;nh mua h&agrave;ng v&agrave; cho những th&ocirc;ng b&aacute;o sau n&agrave;y li&ecirc;n quan đến đơn h&agrave;ng, v&agrave; để cung cấp dịch vụ, bao gồm một số th&ocirc;ng tin c&aacute; nh&acirc;n: danh hiệu, t&ecirc;n, giới t&iacute;nh, ng&agrave;y sinh, email, địa chỉ, địa chỉ giao h&agrave;ng, số điện thoại, fax, chi tiết thanh to&aacute;n, chi tiết thanh to&aacute;n bằng thẻ hoặc chi tiết t&agrave;i khoản ng&acirc;n h&agrave;ng.</p>
                        <p>- Ch&uacute;ng t&ocirc;i sẽ d&ugrave;ng th&ocirc;ng tin qu&yacute; kh&aacute;ch đ&atilde; cung cấp để xử l&yacute; đơn đặt h&agrave;ng, cung cấp c&aacute;c dịch vụ v&agrave; th&ocirc;ng tin y&ecirc;u cầu th&ocirc;ng qua website v&agrave; theo y&ecirc;u cầu của bạn.</p>
                        <p>- Hơn nữa, ch&uacute;ng t&ocirc;i sẽ sử dụng c&aacute;c th&ocirc;ng tin đ&oacute; để quản l&yacute; t&agrave;i khoản của bạn; x&aacute;c minh v&agrave; thực hiện giao dịch trực tuyến, nhận diện kh&aacute;ch v&agrave;o web, nghi&ecirc;n cứu nh&acirc;n khẩu học, gửi th&ocirc;ng tin bao gồm th&ocirc;ng tin sản phẩm v&agrave; dịch vụ. Nếu qu&yacute; kh&aacute;ch kh&ocirc;ng muốn nhận bất cứ th&ocirc;ng tin tiếp thị của ch&uacute;ng t&ocirc;i th&igrave; c&oacute; thể từ chối bất cứ l&uacute;c n&agrave;o.</p>
                        <p>- Ch&uacute;ng t&ocirc;i c&oacute; thể chuyển t&ecirc;n v&agrave; địa chỉ cho b&ecirc;n thứ ba để họ giao h&agrave;ng cho bạn (v&iacute; dụ cho b&ecirc;n chuyển ph&aacute;t nhanh hoặc nh&agrave; cung cấp).</p>
                        <p>- Chi tiết đơn đặt h&agrave;ng của bạn được ch&uacute;ng t&ocirc;i lưu giữ nhưng v&igrave; l&iacute; do bảo mật n&ecirc;n ch&uacute;ng t&ocirc;i kh&ocirc;ng c&ocirc;ng khai trực tiếp được. Tuy nhi&ecirc;n, qu&yacute; kh&aacute;ch c&oacute; thể tiếp cận th&ocirc;ng tin bằng c&aacute;ch đăng nhập t&agrave;i khoản tr&ecirc;n web. Tại đ&acirc;y, qu&yacute; kh&aacute;ch sẽ thấy chi tiết đơn đặt h&agrave;ng của m&igrave;nh, những sản phẩm đ&atilde; nhận v&agrave; những sản phẩm đ&atilde; gửi v&agrave; chi tiết email, ng&acirc;n h&agrave;ng v&agrave; bản tin m&agrave; bạn đặt theo d&otilde;i d&agrave;i hạn.</p>
                        <p>- Qu&yacute; kh&aacute;ch cam kết bảo mật dữ liệu c&aacute; nh&acirc;n v&agrave; kh&ocirc;ng được ph&eacute;p tiết lộ cho b&ecirc;n thứ ba. Ch&uacute;ng t&ocirc;i kh&ocirc;ng chịu bất kỳ tr&aacute;ch nhiệm n&agrave;o cho việc d&ugrave;ng sai mật khẩu nếu đ&acirc;y kh&ocirc;ng phải lỗi của ch&uacute;ng t&ocirc;i.</p>
                        <p>- Ch&uacute;ng t&ocirc;i c&oacute; thể d&ugrave;ng th&ocirc;ng tin c&aacute; nh&acirc;n của bạn để nghi&ecirc;n cứu thị trường. mọi th&ocirc;ng tin chi tiết sẽ được ẩn v&agrave; chỉ được d&ugrave;ng để thống k&ecirc;. Qu&yacute; kh&aacute;ch c&oacute; thể từ chối kh&ocirc;ng tham gia bất cứ l&uacute;c n&agrave;o.</p>
                        <p><strong>2. Bảo mật</strong></p>
                        <p>- Ch&uacute;ng t&ocirc;i c&oacute; biện ph&aacute;p th&iacute;ch hợp về kỹ thuật v&agrave; an ninh để ngăn chặn truy cập tr&aacute;i ph&eacute;p hoặc tr&aacute;i ph&aacute;p luật hoặc mất m&aacute;t hoặc ti&ecirc;u hủy hoặc thiệt hại cho th&ocirc;ng tin của bạn.</p>
                        <p>- Ch&uacute;ng t&ocirc;i khuy&ecirc;n qu&yacute; kh&aacute;ch kh&ocirc;ng n&ecirc;n đưa th&ocirc;ng tin chi tiết về việc thanh to&aacute;n với bất kỳ ai bằng e-mail, ch&uacute;ng t&ocirc;i kh&ocirc;ng chịu tr&aacute;ch nhiệm về những mất m&aacute;t qu&yacute; kh&aacute;ch c&oacute; thể g&aacute;nh chịu trong việc trao đổi th&ocirc;ng tin của qu&yacute; kh&aacute;ch qua internet hoặc email.</p>
                        <p>- Qu&yacute; kh&aacute;ch tuyệt đối kh&ocirc;ng sử dụng bất kỳ chương tr&igrave;nh, c&ocirc;ng cụ hay h&igrave;nh thức n&agrave;o kh&aacute;c để can thiệp v&agrave;o hệ thống hay l&agrave;m thay đổi cấu tr&uacute;c dữ liệu. Nghi&ecirc;m cấm việc ph&aacute;t t&aacute;n, truyền b&aacute; hay cổ vũ cho bất kỳ hoạt động n&agrave;o nhằm can thiệp, ph&aacute; hoại hay x&acirc;m nhập v&agrave;o dữ liệu của hệ thống website. Mọi vi phạm sẽ bị tước bỏ mọi quyền lợi cũng như sẽ bị truy tố trước ph&aacute;p luật nếu cần thiết.</p>
                        <p>- Mọi th&ocirc;ng tin giao dịch sẽ được bảo mật nhưng trong trường hợp cơ quan ph&aacute;p luật y&ecirc;u cầu, ch&uacute;ng t&ocirc;i sẽ buộc phải cung cấp những th&ocirc;ng tin n&agrave;y cho c&aacute;c cơ quan ph&aacute;p luật.</p>
                        <p>C&aacute;c điều kiện, điều khoản v&agrave; nội dung của trang web n&agrave;y được điều chỉnh bởi luật ph&aacute;p Việt Nam v&agrave; t&ograve;a &aacute;n Việt Nam c&oacute; thẩm quyền xem x&eacute;t.</p>
                        <p><strong>3. Quyền lợi kh&aacute;ch h&agrave;ng</strong></p>
                        <p>- Qu&yacute; kh&aacute;ch c&oacute; quyền y&ecirc;u cầu truy cập v&agrave;o dữ liệu c&aacute; nh&acirc;n của m&igrave;nh, c&oacute; quyền y&ecirc;u cầu ch&uacute;ng t&ocirc;i sửa lại những sai s&oacute;t trong dữ liệu của bạn m&agrave; kh&ocirc;ng mất ph&iacute;. Bất cứ l&uacute;c n&agrave;o bạn cũng c&oacute; quyền y&ecirc;u cầu ch&uacute;ng t&ocirc;i ngưng sử dụng dữ liệu c&aacute; nh&acirc;n của bạn cho mục đ&iacute;ch tiếp thị.</p>
                    </div>
                </div>
			</div>
		</div>
	</div>
</section>